steps:
# Build the Docker image with timestamp tag
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/micro-scalp:$BUILD_ID'
    - '-f'
    - 'micro_scalp_engine/Dockerfile.unified'
    - '.'

# Push the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/micro-scalp:$BUILD_ID'

# Also tag as latest
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'tag'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/micro-scalp:$BUILD_ID'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/micro-scalp:latest'

# Push latest tag
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/micro-scalp:latest'

options:
  logging: CLOUD_LOGGING_ONLY 